"""area table

Revision ID: 4f463d6ee5ba
Revises: c5d14d2e46f9
Create Date: 2022-08-03 12:31:28.781746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f463d6ee5ba'
down_revision = 'c5d14d2e46f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_location'), 'area', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_location'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
